from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(Donations)
admin.site.register(Rasxod)
admin.site.register(EventCategory)
admin.site.register(Event)
admin.site.register(NewsCategory)
admin.site.register(Country)
admin.site.register(Hashtag)
admin.site.register(News)
admin.site.register(NewsHashtagRelation)
admin.site.register(MapPoint)
admin.site.register(UsefulLink)
admin.site.register(FollowUsPost)
admin.site.register(Chairman)
admin.site.register(Task)
admin.site.register(Representative)
admin.site.register(Vacancy)
admin.site.register(Resume)
admin.site.register(ScheduledEventCategory)
admin.site.register(ScheduledEvent)
admin.site.register(Feedback)
admin.site.register(Question)
admin.site.register(Faq)
admin.site.register(Service)
admin.site.register(Gallery)
admin.site.register(MigrationLaw)
admin.site.register(Consul)
admin.site.register(Volunteer)
admin.site.register(Book)
admin.site.register(Language)
admin.site.register(LawOfCountry)
admin.site.register(University)
admin.site.register(Faculty)
admin.site.register(Region)
admin.site.register(Intern)
admin.site.register(InstagramPost)