# Generated by Django 4.1.7 on 2023-03-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairman',
            name='avatar_compressed',
            field=models.ImageField(blank=True, upload_to='photos/avatar%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='avatar_original',
            field=models.ImageField(blank=True, upload_to='photos/avatar%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='reception_days',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chairman',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='donations',
            name='status_id',
            field=models.BooleanField(help_text='True for payed, False for not payed status'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type_id',
            field=models.CharField(help_text='enter a type 1 --> for employees 2 --> for volunteers', max_length=1),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='logo_poster_path',
            field=models.ImageField(blank=True, upload_to='photos/logo%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='usefullink',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_type',
            field=models.CharField(help_text='enter a type of work part-time(0.5) or full_time', max_length=20),
        ),
    ]
